- bnf_bo_config.rb
- bnf_cealex_config.rb
- bnf_ebaf_config.rb
- bnf_ideo_config.rb
- bnf_ifao_config.rb
- bnf_ifea_config.rb
- bnf_salt_config.rb
> fix agg_is_shown_at and agg_preview to adhere to correct json format

- .rubocop.yml
- bnf_bo_config.rb
- bnf_cealex_config.rb
- bnf_common_config.rb
- bnf_ebaf_config.rb
- bnf_ideo_config.rb
- bnf_ifao_config.rb
- bnf_ifea_config.rb
- bnf_salt_config.rb
fixes #5 The only repetition now is the record variable that is repeated in all 8 bnf files. If it could be added to the common file and made available to the other 7 this would be preferable, I think. I haven't figured that out so opened #7
> refactor bnf config to eliminate repetition

- metadata_mapping.json
refs https://github.com/sul-dlss/dlme-transform/issues/85
> Adds metadata_mapping.json

- fgdc_config.rb
> Updates fgdc_config with correct macros.

- README.md
> Add example documentation

- bnf_common_config.rb
> add cho_provenance per data agreement

- bnf_common_config.rb
- bnf_salt_config.rb
> Updated bnf configs to traject3.

- sakip_sabanci_config.rb
~~Not finding anything with current xpath queries...need to debug~~
> Ssm config

- sakip_sabanci_config.rb
Somehow I deleted the downcase
> add downcase back in

- bnf_common_config.rb
Use the Traject 3 methods instead
Depends on https://github.com/sul-dlss/dlme-transform/pull/115
> Avoid deprecated transforms passed to traject_plus macros

- bnf_common_config.rb
Depends on https://github.com/sul-dlss/dlme-transform/pull/118
> Use the new SRW macros for link and thumbnail

- sakip_sabanci_config.rb
@peetucket, @justinlittman can one of you please review and merge this so I can resume testing?
> use extract_oai_identifier

- marc_config.rb
- tei_config.rb
fixes dlme-transform#117 and dlme-transform#119
> refactor penn configs language field

- metadata_mapping.json
- qnl_config.rb
fixes https://github.com/sul-dlss/dlme-traject/issues/50
Lines 18-31 should probably be broken out into a separate macro. There is a `mods.rb` here: https://github.com/sul-dlss/dlme-transform/blob/master/lib/macros/mods.rb and a `mods_config.rb` here: https://github.com/sul-dlss/dlme-traject/blob/master/mods_config.rb but neither of them work as is. I wasn't sure if I should try to extend them or write a new macro so I just decided to put everything in the config and leave it to @jcoyne and/or @justinlittman to decide if they want to refactor.
> QNL config

- penn_egyptian_config.rb
- penn_near_east_config.rb
fixes https://github.com/sul-dlss/dlme-transform/issues/129
> fix missing title error in penn data

- metadata_mapping.json
- yale_medical_config.rb
fixes https://github.com/sul-dlss/dlme-traject/issues/43
@anarchivist Wayne couldn't remember what needed to be done with all of this legacy data but since he created a ticket for it I went ahead and wrote the config.
> write yale config

- metadata_mapping.json
- stanford_mods_config.rb
Refs https://github.com/sul-dlss/dlme-transform/issues/147
Adds the stanford_mods back into the config and fixes the require for IIIF.fetch_manifest.
> Use stanford mods

- stanford_mods_config.rb
* Cache retrieval of Stanford IIIF manifest in the Traject context
* Generate thumbnail URI for geo resources without IIIF manifests
ref sul-dlss/dlme-transform#147 and #74
> Improve logic to generate Stanford thumbnails/IIIF resources

- .circleci/config.yml
- README.md
> add ci build badge to README

- tei_config.rb
OCD?   I was having trouble comparing similar lines?   A bumblebee distracted me?
n/a
> tei_config: make alignment more consistent

- metadata_mapping.json
Add country values to the metadata mappings to drive data dashboard.
Yes
> Add country values to metadata mapping, closes #111

- metadata_mapping.json
Add Arabic country and data provider values for Arabic interface
NA
> add Arabic country and provider values

- openn_config.rb
Use the new language normalization macro in openn_config
NA
> Normalize openn

- aims_config.rb
- aub_common_config.rb
- auc_config.rb
- bnf_common_config.rb
- bodleian_config.rb
- cambridge_config.rb
- cluster_config.rb
- csv_config.rb
- fgdc_config.rb
- harvard_ihp_config.rb
- iiif_config.rb
- marc_config.rb
- met_config.rb
- michigan_config.rb
- mods_config.rb
- numismatic_csv_config.rb
- openn_config.rb
- penn_museum_config.rb
- pppa_config.rb
- princeton_movie_config.rb
- princeton_mss_config.rb
- qnl_config.rb
- sakip_sabanci_config.rb
- stanford_mods_config.rb
update configs to add Arabic country and data providers
yes
> update configs to add Arabic country and data providers, closes dlme-transform#172

- mods_config.rb
- Uses new normalization macro
NA
> use new macro for type normalization

- README.md
- aims_config.rb
- aub_common_config.rb
- auc_config.rb
- bnf_common_config.rb
- bodleian_config.rb
- cambridge_config.rb
- cluster_config.rb
- csv_config.rb
- fgdc_config.rb
- harvard_ihp_config.rb
- iiif_config.rb
- marc_config.rb
- met_config.rb
- michigan_config.rb
- mods_config.rb
- numismatic_csv_config.rb
- openn_config.rb
- penn_museum_config.rb
- pppa_config.rb
- princeton_movie_config.rb
- princeton_mss_config.rb
- qnl_config.rb
- sakip_sabanci_config.rb
- stanford_mods_config.rb
- yale_medical_config.rb
_DO NOT MERGE_ until the associated dlme-transform PR merged (changing validation for the affected fields)
Fixes #139
Yes
> Map provider-related fields into new language hash in both English and Arabic
